apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: golang
        image: gcr.io/k8s-examples-316720/goapp-example:latest
        ports:
        - containerPort: 3000