apiVersion: v1
kind: Service
metadata:
  name: golang-deployment
spec:
  type: ClusterIP
  selector:
    app: golang
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
